model_list:
  # OpenAI
  - model_name: gpt-5.2
    litellm_params:
      model: openai/gpt-5.2
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-5.2-2025-12-11
    litellm_params:
      model: openai/gpt-5.2-2025-12-11
      api_key: os.environ/OPENAI_API_KEY
  - model_name: codex-mini-latest
    litellm_params:
      model: openai/codex-mini-latest
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-4-0613
    litellm_params:
      model: openai/gpt-4-0613
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-5
    litellm_params:
      model: openai/gpt-5
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-5-mini
    litellm_params:
      model: openai/gpt-5-mini
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-5-nano
    litellm_params:
      model: openai/gpt-5-nano
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-5-chat-latest
    litellm_params:
      model: openai/gpt-5-chat-latest
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-5-2025-08-07
    litellm_params:
      model: openai/gpt-5-2025-08-07
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-5-mini-2025-08-07
    litellm_params:
      model: openai/gpt-5-mini-2025-08-07
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-5-nano-2025-08-07
    litellm_params:
      model: openai/gpt-5-nano-2025-08-07
      api_key: os.environ/OPENAI_API_KEY
  - model_name: o3-pro
    litellm_params:
      model: openai/o3-pro
      api_key: os.environ/OPENAI_API_KEY
  - model_name: o3
    litellm_params:
      model: openai/o3
      api_key: os.environ/OPENAI_API_KEY
  - model_name: o4-mini
    litellm_params:
      model: openai/o4-mini
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-4.1
    litellm_params:
      model: openai/gpt-4.1
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-4.1-mini
    litellm_params:
      model: openai/gpt-4.1-mini
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-4.1-nano
    litellm_params:
      model: openai/gpt-4.1-nano
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-4.5-preview
    litellm_params:
      model: openai/gpt-4.5-preview
      api_key: os.environ/OPENAI_API_KEY
  - model_name: o1-pro
    litellm_params:
      model: openai/o1-pro
      api_key: os.environ/OPENAI_API_KEY
  - model_name: o3-mini
    litellm_params:
      model: openai/o3-mini
      api_key: os.environ/OPENAI_API_KEY
  - model_name: o1
    litellm_params:
      model: openai/o1
      api_key: os.environ/OPENAI_API_KEY
  - model_name: o1-preview
    litellm_params:
      model: openai/o1-preview
      api_key: os.environ/OPENAI_API_KEY
  - model_name: o1-mini
    litellm_params:
      model: openai/o1-mini
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-4o-mini
    litellm_params:
      model: openai/gpt-4o-mini
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-4o
    litellm_params:
      model: openai/gpt-4o
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-4-turbo
    litellm_params:
      model: openai/gpt-4-turbo
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: openai/gpt-3.5-turbo
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-4
    litellm_params:
      model: openai/gpt-4
      api_key: os.environ/OPENAI_API_KEY
  - model_name: text-embedding-3-large
    litellm_params:
      model: openai/text-embedding-3-large
      api_key:  os.environ/OPENAI_API_KEY
    model_info:
      mode: embedding
  - model_name: text-embedding-3-small
    litellm_params:
      model: openai/text-embedding-3-small
      api_key:  os.environ/OPENAI_API_KEY
    model_info:
      mode: embedding

  # Anthropic/Claude
  - model_name: claude-opus-4-5-20251101
    litellm_params:
      model: anthropic/claude-opus-4-5-20251101
      api_key: os.environ/ANTHROPIC_API_KEY
  - model_name: claude-sonnet-4-5-20250929
    litellm_params:
      model: anthropic/claude-sonnet-4-5-20250929
      api_key: os.environ/ANTHROPIC_API_KEY
  - model_name: claude-haiku-4-5-20251001
    litellm_params:
      model: anthropic/claude-haiku-4-5-20251001
      api_key: os.environ/ANTHROPIC_API_KEY
  - model_name: claude-opus-4-1-20250805
    litellm_params:
      model: anthropic/claude-opus-4-1-20250805
      api_key: os.environ/ANTHROPIC_API_KEY
  - model_name: claude-sonnet-4-20250514
    litellm_params:
      model: anthropic/claude-sonnet-4-20250514
      api_key: os.environ/ANTHROPIC_API_KEY
  - model_name: claude-opus-4-20250514
    litellm_params:
      model: anthropic/claude-opus-4-20250514
      api_key: os.environ/ANTHROPIC_API_KEY
  - model_name: claude-3-7-sonnet-20250219
    litellm_params:
      model: anthropic/claude-3-7-sonnet-20250219
      api_key: os.environ/ANTHROPIC_API_KEY
  - model_name: claude-3-opus-20240229
    litellm_params:
      model: anthropic/claude-3-opus-20240229
      api_key: os.environ/ANTHROPIC_API_KEY
  - model_name: claude-3-5-sonnet-20241022
    litellm_params:
      model: anthropic/claude-3-5-sonnet-20241022
      api_key: os.environ/ANTHROPIC_API_KEY
  - model_name: claude-3-5-haiku-20241022
    litellm_params:
      model: anthropic/claude-3-5-haiku-20241022
      api_key: os.environ/ANTHROPIC_API_KEY
  - model_name: claude-3-sonnet-20240229
    litellm_params:
      model: anthropic/claude-3-sonnet-20240229
      api_key: os.environ/ANTHROPIC_API_KEY
  - model_name: claude-3-haiku-20240307
    litellm_params:
      model: anthropic/claude-3-haiku-20240307
      api_key: os.environ/ANTHROPIC_API_KEY

  # Google/Gemini
  - model_name: gemini-3-flash-preview
    litellm_params:
      model: gemini/gemini-3-flash-preview
      api_key:  os.environ/GEMINI_API_KEY
  - model_name: gemini-3-pro-preview
    litellm_params:
      model: gemini/gemini-3-pro-preview
      api_key:  os.environ/GEMINI_API_KEY
  - model_name: gemini-3-pro-image-preview
    litellm_params:
      model: gemini/gemini-3-pro-image-preview
      api_key:  os.environ/GEMINI_API_KEY
  - model_name: gemini-2.5-pro
    litellm_params:
      model: gemini/gemini-2.5-pro
      api_key:  os.environ/GEMINI_API_KEY
  - model_name: gemini-2.5-flash
    litellm_params:
      model: gemini/gemini-2.5-flash
      api_key:  os.environ/GEMINI_API_KEY
  - model_name: gemini-2.0-flash-thinking-exp-1219
    litellm_params:
      model: gemini/gemini-2.0-flash-thinking-exp-1219
      api_key:  os.environ/GEMINI_API_KEY
  - model_name: gemini-2.0-flash-thinking-exp
    litellm_params:
      model: gemini/gemini-2.0-flash-thinking-exp
      api_key:  os.environ/GEMINI_API_KEY
  - model_name: gemini-2.0-flash-exp
    litellm_params:
      model: gemini/gemini-2.0-flash-exp
      api_key:  os.environ/GEMINI_API_KEY
  - model_name: gemini-2.0-flash-lite
    litellm_params:
      model: gemini/gemini-2.0-flash-lite
      api_key:  os.environ/GEMINI_API_KEY
  - model_name: gemini-2.0-flash
    litellm_params:
      model: gemini/gemini-2.0-flash
      api_key:  os.environ/GEMINI_API_KEY
  - model_name: gemini-1.5-flash
    litellm_params:
      model: gemini/gemini-1.5-flash
      api_key:  os.environ/GEMINI_API_KEY
  - model_name: gemini-1.5-flash-8b
    litellm_params:
      model: gemini/gemini-1.5-flash-8b
      api_key:  os.environ/GEMINI_API_KEY
  - model_name: gemini-1.5-pro
    litellm_params:
      model: gemini/gemini-1.5-pro
      api_key:  os.environ/GEMINI_API_KEY
  - model_name: text-embedding-004
    litellm_params:
      model: gemini/text-embedding-004
      api_key:  os.environ/GEMINI_API_KEY
    model_info:
      mode: embedding

  # XAI
  - model_name: grok-4-0709
    litellm_params:
      model: xai/grok-4-0709
      api_key:  os.environ/XAI_API_KEY
  - model_name: grok-3-beta
    litellm_params:
      model: xai/grok-3-beta
      api_key:  os.environ/XAI_API_KEY
  - model_name: grok-3-fast-beta
    litellm_params:
      model: xai/grok-3-fast-beta
      api_key:  os.environ/XAI_API_KEY
  - model_name: grok-3-mini-beta
    litellm_params:
      model: xai/grok-3-mini-beta
      api_key:  os.environ/XAI_API_KEY
  - model_name: grok-3-mini-fast-beta
    litellm_params:
      model: xai/grok-3-mini-fast-beta
      api_key:  os.environ/XAI_API_KEY
  - model_name: grok-3
    litellm_params:
      model: xai/grok-3
      api_key:  os.environ/XAI_API_KEY
  - model_name: grok-3-fast
    litellm_params:
      model: xai/grok-3-fast
      api_key:  os.environ/XAI_API_KEY
  - model_name: grok-3-mini
    litellm_params:
      model: xai/grok-3-mini
      api_key:  os.environ/XAI_API_KEY
  - model_name: grok-3-mini-fast
    litellm_params:
      model: xai/grok-3-mini-fast
      api_key:  os.environ/XAI_API_KEY
