model_list:
  - model_name: claude-opus-4-5-20251101
    litellm_params:
      model: anthropic/claude-opus-4-5-20251101
      api_key: os.environ/ANTHROPIC_API_KEY
      # Originally tested with nesting LiteLLM proxies
      # api_key: os.environ/LITELLM_KEY
      # api_base: https://litellm.example.com:4000
