atlantis-vincent:
  models:
    - claude sonnet 4.5
  cpu: "all"
  ram: 4G
  dependencies: []
  features: []

build:  # optional, by default builder.Dockerfile
 dockerfile: oss-patch/claude-code.builder.Dockerfile
