atlantis-multi-retrieval:
  models:
    - gpt-o4-mini
  cpu: "all"
  ram: 4G
  dependencies: []
  features: []

build:  # optional, by default builder.Dockerfile
 dockerfile: oss-patch/multi-retrieval.builder.Dockerfile
