swe-agent:
  models:
    - gemini-2.5-pro
  cpu: "all"
  ram: 4G
  dependencies: []
  features: []

build:  # optional, by default builder.Dockerfile
 dockerfile: oss-patch/swe-agent.builder.Dockerfile
