# Runtime environment variables for CRS
# These are merged with .env (which can override)
atlantis-multilang-given_fuzzer:
  models: []
  modes:
    - full
    - delta
  prepare:
    bake_file: docker-bake.hcl
    target: prepare
  build:
    dockerfile: builder.Dockerfile
  run:
    dockerfile: runner.Dockerfile
